### ISSUE TITLE
Setup Tito With Wave Tickets

### ISSUE THREAD

**Issue by seanmerron** [HRDevFest/Planning#14]
- [x] 50% student discount code.
- [x] free code for issuetrak attendees / other sponsor free tickets based on sponsor package
- [x] free code for organizers
- [x] Discount and/or first dibs for Alumni and RevConf attendees
- [x] $29 50 tickets each wave
- [x] $39 50 tickets each wave
- [x] $49 50 tickets each wave
- [x] 150 total tickets including everyone
- [ ] Remind attendees to bring power strips

**Comment by 1kevgriff** [comment]
v1 - https://ti.to/deved-llc/hrdevfest-2016

**Comment by 1kevgriff** [comment]
@seanmerron For alumni discounts, I was thinking 15% and limiting to 25 tickets?  Thoughts?

**Comment by 1kevgriff** [comment]
Student link :https://ti.to/revolutionva/hrdevfest-2016/discount/ENHANCEDEDUCATION
50% any ticket - limit 25

**Comment by 1kevgriff** [comment]
@seanmerron IssueTrak/Sponsors?  Combine into single secret ticket type?  Let's save this for when sponsor package is figured out.

**Comment by seanmerron** [comment]
@1kevgriff maybe we just make the alumni discount until wave 1 sells out to all past and revconf attendees
Yeah I'm good with secret ticket type for sponsors. We have the packages figured out on the Google drive
