### ISSUE TITLE
Purchase Event Insurance

### ISSUE THREAD

**Issue by seanmerron** [HRDevFest/Planning#25]
Determine Alcohol liability

**Comment by switchspan** [comment]
Determine Sean Merron liability

**Comment by seanmerron** [comment]
That may be hard to find coverage for! Dude is wreckless..

**Comment by erikpmp** [comment]
I requested a quote for $1M coverage. Should be about $150 which is what we paid for RevolutionConf coverage. If it's in the $150 neighborhood then I'll just go ahead and secure it. I'll update this task when the quote comes in.

**Comment by erikpmp** [comment]
I got an initial quote of $150-ish which included an alcohol rider. Now just waiting for the final certificate of insurance.

**Comment by erikpmp** [comment]
Received.

[2016-07-01 Insurance for HRDevFest 2016.pdf](https://github.com/HRDevFest/Planning/files/343916/2016-07-01.Insurance.for.HRDevFest.2016.pdf)
