### ISSUE TITLE
Create Generic Code of Conference

### ISSUE THREAD

**Issue by seanmerron** [HRDevFest/Planning#27]

**Comment by lynnaloo** [comment]
https://github.com/HRDevFest/Planning/blob/master/CODE-OF-CONDUCT.md. @seanmerron do you want to add this to the website as well?

**Comment by seanmerron** [comment]
@lynnaloo awesome! Yes will link to this. I noticed one section with revolutionconf mentioned. We can edit to have attendees look for staff signified by different color lanyards since we'll have the same shirts.
