### ISSUE TITLE
Figure out Non-Profit Legal

### ISSUE THREAD

**Issue by seanmerron** [HRDevFest/Planning#3]
To be assigned to Erik...

Consider rename?

**Comment by erikpmp** [comment]
I've contacted the lawyers about expanding the RevConf BoD to include the HeDevFest board members and Alex. I'll check on status today. 

We need to agree on new name for non profit. I'll take lead on that.

**Comment by seanmerron** [comment]
Awesome! I agree on the name change as it seems there could be a vision to use the 501c3 for more than just conferences to continue shaping the local tech community. Revoluton Devents 501c3 :-)

**Comment by erikpmp** [comment]
All paperwork done. Closing
